version: 0.1

environmentVariables: 
    plaintext:
        AWS_DEFAULT_REGION: "us-west-2"
        AWS_ACCOUNT_ID: "708547824206"
        IMAGE_REPO_NAME: "example123"
        IMAGE_TAG: "latest"

phases:
  install:
    commands:
      - echo Installing NPM and NodeJS
      - sudo apt-get --yes --force-yes update
      - sudo apt-get --yes --force-yes install nodejs
      - sudo apt-get --yes --force-yes install npm
      - echo Installing Mocha...
      - npm install -g mocha
      - echo Mocha installed
      - ln -s /usr/bin/nodejs /usr/bin/node
      - node -v
      - npm -v
      - mocha -V
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - npm install
      - npm run test
      - echo Build started on `date`
      - echo Building the Docker image...        
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG